spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ezoz_backend_dev?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none

google:
  client:
    id: ENC(jyFppUjjpuMriawAwTyuZuZ+CunF9q/GMsh5Kyohp27vMbV/Rw/M/sCEuTMVl2JdftTWIf7lJqVcURGdJqzbWCTgS/Y9xgLT+txoFScBckJII40YejzrcQ==)
    secret: ENC(FJGpnbaGoFG5QyNSvsUxc26AHVg6wq8QzLmWZTgyRwQIggU05kaOdoBxtIXdz1iH)
  callback-uri: http://localhost:8080/google/code

elastic:
  url: localhost:9200
#google:
#  client:
#    id: ENC(6SOx0fH70XMUW9lCNpbDnckPTDRbNUr+HiRMXUauNj3/dLFKwA9Xt+YCaBx9jFqX4jYMsxSjmDFmP3SoehRXdM5O4FHJTBggVqQDdEgXgoeCOPvWW/pzaw==)
#    secret: ENC(4M4MOcL7TbifTjpLyzQPVcHOCN5ToVqiAMaZGieLmEHLsqhnScveoGbBB4O21WRj)
#  callback-uri: http://localhost:8080/google/code