spring:
  datasource:
    url: ENC(co2H13lJBbPq7z5xZfN9GlTwC5eB1CfdSLPGaf2al5+LEPdKKAGF3IeQMYAegkWLkEFlgQBlMNgwHh4JWY0cBRKjftmfuWKkGcuvuiZgpG6SnpVMzqrvpw==)
    username: ENC(c9Jr2EahcS7yKfS+CcG5pw==)
    password: ENC(MbOoE7cvhVipq5ggrrUUOA==)
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
