spring:
  profiles:
    default: local
  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100

    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 100MB # 파일 업로드 요청 시 하나의 파일 크기 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일의 크기의합 100MB로 제한

logging:
  level:
    org.hibernate.type: trace
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE=TRACE: trace

cloud:
  aws:
    bucket: ezoz-image-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

token:
  secret: ENC(lDOPPFP+MfO0vqmgDit4eh5IqSaI496Up23uqnvldVOhbpcqgNiSVtvyxsEQkhqOWtg/ZaguUE/J+pHkx5rMSAXORW4EAbV/mCUEBQ8bY4aKrZmreJviie8ZGYjzKDE5IFFVMcbxxiVzUqSg5Fuajg==)
  access-token-expiration-time: 900000  # 15분
  refresh-token-expiration-time: 1210500000 # 2주

kakao:
  client:
    secret: ENC(B+UHkjDDMf3BBzsVcbGvM21DTyuXorOiGF+kUVqtR45vugBoEIyGNo43O6lYgtJ6)
    id: ENC(y4WHYqeOsIIVP5kn0yCeSrfJceGTj5Qj6AXluMz5Q2V7DF8/618hZXE3ITRgadFk)
  redirect-uri: https://ezoz-trip.com/auth/kakao/callback

iam:
  accesskey: ENC(Dehtcz7lSAM9gCvURBemyGKOXub28+FkLS4UEuyi2UQ=)
  secretkey: ENC(puuXilnCaEbu+lLxCpRFFIcpj1FOGeNCMzm0/RdDHNPq62qUjzJy+N7OZw2mqb8N2n7uhiypNgY=)



